### PR TITLE
Add default ports for all services

### LINKED ISSUE #151: Add Default Ports for All Services
Use the following Ports:
user service: 15551
registration: 15552
identity: 15553
notifications: 15554
otp: 15555

In addition, set all values for server.port to 8080 on prod configuration (since that configuration is used for docker and kube).

### PR DESCRIPTION
**Pull request by IEnoobong**
closes #151

### CODE REVIEW

**Comment by geraldoyudo** [comment]
You'll need to add explicit server.port=8080 to all services in prod configuration if not, they will inherit what you added for the default configuration

**Comment by geraldoyudo** [comment]
I think you should make a Pull Request instead of merge request so that this will pass through the repository's CI. Set your origin to this repo instead, push the branch and make a pull request.

**Comment by IEnoobong** [comment]
> I think you should make a Pull Request instead of merge request so that this will pass through the repository's CI. Set your origin to this repo instead, push the branch and make a pull request.

Hmm, I couldn't push a branch to this repo, permission issues

```
remote: Permission to geraldoyudo/mmadu.git denied to IEnoobong.
fatal: unable to access 'https://github.com/geraldoyudo/mmadu.git/': The requested URL returned error: 403
```

@geraldoyudo

**Comment by geraldoyudo** [comment]
@IEnoobong, I've invited you to be a collaborator for this repo. Thanks.

**Comment by IEnoobong** [comment]
Got it, closing in favor of https://github.com/geraldoyudo/mmadu/pull/153

**Pull request closed without merging**
